/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubIndexRouteImport } from './routes/club/index'
import { Route as ClubRatingRouteImport } from './routes/club/rating'
import { Route as ClubRulesRouteImport } from './routes/club/rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/club/',
  path: '/club/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRatingRoute = ClubRatingRouteImport.update({
  id: '/club/rating',
  path: '/club/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRulesRoute = ClubRulesRouteImport.update({
  id: '/club/rules',
  path: '/club/rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club/rating': typeof ClubRatingRoute
  '/club/rules': typeof ClubRulesRoute
  '/club/': typeof ClubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club/rating': typeof ClubRatingRoute
  '/club/rules': typeof ClubRulesRoute
  '/club': typeof ClubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club/rating': typeof ClubRatingRoute
  '/club/rules': typeof ClubRulesRoute
  '/club/': typeof ClubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/club/rating' | '/club/rules' | '/club/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/club/rating' | '/club/rules' | '/club'
  id: '__root__' | '/' | '/club/rating' | '/club/rules' | '/club/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRatingRoute: typeof ClubRatingRoute
  ClubRulesRoute: typeof ClubRulesRoute
  ClubIndexRoute: typeof ClubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/club'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/rating': {
      id: '/club/rating'
      path: '/club/rating'
      fullPath: '/club/rating'
      preLoaderRoute: typeof ClubRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/rules': {
      id: '/club/rules'
      path: '/club/rules'
      fullPath: '/club/rules'
      preLoaderRoute: typeof ClubRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRatingRoute: ClubRatingRoute,
  ClubRulesRoute: ClubRulesRoute,
  ClubIndexRoute: ClubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
